[package]
name = "weak_list"
version = "0.2.0"
authors = ["uHOOCCOOHu <hooccooh1896@gmail.com>"]
description = "Strict weak lists"
repository = "https://github.com/uHOOCCOOHu/weak_list"
license = "MIT"
keywords = ["containers", "Rc", "Arc", "weak"]

[dependencies]
